apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool
spec:
  selector:
    matchLabels:
      app: busybox-multitool
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while sleep 5; do date; done >> /vol01/watchdog;']
        volumeMounts:
        - name: vol01
          mountPath: /vol01
      - name: multitool
        image: praqma/network-multitool
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vol01
          mountPath: /vol01
      volumes:
      - name: vol01
        persistentVolumeClaim:
          claimName: pv01-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv01-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi